- name: Check if we've previously completed this step
  ansible.builtin.stat:
    path: /usr/local/etc/.breadcrumb_gh_secrets_updated
  register: breadcrumb_gh_secrets_updated

- name: Create SSH key and upload

  block:

  - name: Pause for GitHub Personal Access Token input
    ansible.builtin.pause:
      prompt: "Please enter your GitHub Personal Access Token"
    register: gh_pat

  # Generate and install key into host
  -  name: Generate SSH key pair for GitHub Actions
     ansible.builtin.openssh_keypair:
       path: /home/cartogram/tmp_ghactions_key
       type: rsa
       size: 4096
       state: present
     register: ssh_keypair

  -  name: Install the public SSH key into authorized_keys for cartogram
     ansible.builtin.authorized_key:
       user: cartogram
       state: present
       key: "{{ ssh_keypair.public_key }}"

  # Update GitHub secrets for go-cart-io/cartogram-docker
  - name: Update SERVER_SSH_ACCESS_KEY in go-cart-io/cartogram-docker's GitHub secrets
    ansible.builtin.shell:
      cmd: "cat /home/cartogram/tmp_ghactions_key | ghupdatesecret go-cart-io/cartogram-docker SERVER_SSH_ACCESS_KEY -u {{ github_username }} -p {{ gh_pat.user_input }}"

  - name: Update SERVER_HOSTNAME in go-cart-io/cartogram-docker's GitHub secrets
    ansible.builtin.shell:
      cmd: "echo {{ ansible_ssh_host }} | ghupdatesecret go-cart-io/cartogram-docker SERVER_HOSTNAME -u {{ github_username }} -p {{ gh_pat.user_input }}"

  - name: Clean up
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/home/cartogram/tmp_ghactions_key"
      - "/home/cartogram/tmp_ghactions_key.pub"

  - name: Create marker file to indicate SSH key setup completion
    become_user: root
    ansible.builtin.file:
      path: /usr/local/etc/.breadcrumb_gh_secrets_updated
      state: touch

  when: not breadcrumb_gh_secrets_updated.stat.exists